/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ARefree: typeof import('./src/components/refree/aRefree/ARefree.vue')['default']
    DRefree: typeof import('./src/components/refree/dRefree/DRefree.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ERefree: typeof import('./src/components/refree/eRefree/ERefree.vue')['default']
    EyeRefree: typeof import('./src/components/refree/eyeRefree/EyeRefree.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MatchList: typeof import('./src/components/match/MatchList.vue')['default']
    RefreeEmpty: typeof import('./src/components/common/RefreeEmpty.vue')['default']
    RefreeRole: typeof import('./src/components/refree/refreeRole/RefreeRole.vue')['default']
    RefreeRoleGroup: typeof import('./src/components/refree/refreeRole/RefreeRoleGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreHeader: typeof import('./src/components/common/ScoreHeader.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
  }
}
